[workspace]
members = [
    "aoc2021-day1",
    "aoc2021-day2",
    "aoc2021-day3",
    "aoc2021-day4",
    "aoc2021-day5",
    "aoc2021-day6",
    "aoc2021-day7",
    "aoc2021-day8",
    "utils"
]

[profile.release]
opt-level = "s"
